export const mockUsersData = {
    user: [{
        "firstName": "Art",
        "lastName": "Nelson",
        "email": "artnelson0@gamil.com",
        "password": "ow7378rDFxs"
      }, {
        "firstName": "Bernard",
        "lastName": "Ricardo",
        "email": "bricardo1@hotmail.com",
        "password": "wtj3736HAvY"
      }, {
        "firstName": "Base",
        "lastName": "Odin",
        "email": "baseodin2@webs.com",
        "password": "oE4948ru3NR1"
      }, {
        "firstName": "Susannah",
        "lastName": "Voe",
        "email": "svlasov4@about.com",
        "password": "guM17537"
      }, ]}